### PR TITLE
multiple scopes

### PR DESCRIPTION
**Pull request by dominictarr**
update default config to support multiple scopes

depends on: https://github.com/ssbc/multiserver/pull/32

### CODE REVIEW

**Comment by arj03** [comment]
Was this supposed to be included in 13.1 @dominictarr? Also would be good with an README update with examples of the new mode.

**Comment by dominictarr** [comment]
uh yeah I think it was. @mixmix seems to have discovered a quirk that was letting tests pass without this
https://github.com/ssbc/ssb-server/issues/614

**Comment by dominictarr** [comment]
I wasn't 100% sure that this wouldn't break anything, so I merged bumped to 3.0.0

**Comment by mixmix** [comment]
except it looks like you didn't merge this successfully  @dominictarr ... not sure what you did exactly.
I fixed this, merged this branch and published as 3.0.1

**Comment by mixmix** [comment]
oh thank you so much for filling in the README scopes section. That's gonna help me do something like write test or schema to make these safer

re : ff10ce15844ed5ec5d2a0db2b39ac5bb349236a4

**Pull request merged**
