### PR TITLE
Add connections

### PR DESCRIPTION
**Pull request by arj03**
Add defaults for connections.

### CODE REVIEW

**Comment by staltz** [comment]
Good to merge in my opinion

**Comment by arj03** [comment]
Thanks for having a look staltz. I'll wait with merging this as its rather small and until we have the secret-stack [changes](https://github.com/ssbc/secret-stack/pull/23) merged. After that it should be a matter of getting this [scuttlebot](https://github.com/ssbc/scuttlebot/tree/multiserver-config-scope) change merged. ssb-client is already ready :)

I havn't heard dominics opinions on the scope changes, so would rather wait with merging these things until he has had time to look it over. 

Very happy that you are already testing this in mmmm and thanks for fixing the multiserver problem.

**Comment by cryptix** [comment]
I rebased this on 2.2.1 and wrote a little more about how to use the two connection objects.

**Comment by dominictarr** [comment]
merged into 2.3.0

**Pull request merged**
