### PR TITLE
default to a more safe address

### PR DESCRIPTION
**Pull request by dominictarr**
this should resolve https://github.com/ssbc/scuttlebot/pull/102
at least, on @pfraze's laptop.

### CODE REVIEW

**Comment by pfraze** [comment]
ok, lets try it

**Comment by pfraze** [comment]
published `1.0.2`

**Comment by pfraze** [comment]
@dominictarr i dont have publish rights, you'll need to pull and publish. Repo has already had its version bumped, no need to do that again.

**Comment by pfraze** [comment]
appears to work, but I'm now getting network interface info spit out in the console:

```
:~/scuttlebot$ ./bin.js whoami
{ address: '::1', family: 'IPv6', internal: true }
{ address: '127.0.0.1', family: 'IPv4', internal: true }
{ address: 'fe80::1', family: 'IPv6', internal: true }
{ address: 'fe80::2ef0:eeff:fe01:839c',
  family: 'IPv6',
  internal: false }
{ address: '2605:6000:e900:d200:2ef0:eeff:fe01:839c',
  family: 'IPv6',
  internal: false }
{ address: '2605:6000:e900:d200:f4bb:ab57:1a39:ac9',
  family: 'IPv6',
  internal: false }
{ address: '192.168.0.2', family: 'IPv4', internal: false }
{ address: 'fe80::184a:a8ff:fe2d:54ce',
  family: 'IPv6',
  internal: false }
{ address: '::1', family: 'IPv6', internal: true }
{ address: '127.0.0.1', family: 'IPv4', internal: true }
{ address: 'fe80::1', family: 'IPv6', internal: true }
{ address: 'fe80::2ef0:eeff:fe01:839c',
  family: 'IPv6',
  internal: false }
{
  "id": "3SIcT+ckwPPCl77ClMf0t+bioqqKWTGMVuWS0y2ZvpM=.blake2s",
  "public": "Ic/pwbP5h8pPVjHx1eZEOXG/hcDmf5PxXIaiPBe7/S0oj/EN/EEdpavvPE7i4xstnOgw2H2prYbsJHiVOqbh2w==.k256"
}
```

**Comment by dominictarr** [comment]
oops, update non-private-ip to 1.2.1

**Comment by pfraze** [comment]
@dominictarr have you published 1.2.1 yet?

**Comment by dominictarr** [comment]
oops, published.

**Pull request merged**
