### PR TITLE
change default port from 2000 to 8008

### PR DESCRIPTION
**Pull request by ralphtheninja**
Fixes https://github.com/ssbc/phoenix/issues/306

### CODE REVIEW

**Comment by pfraze** [comment]
:+1: This is the first of a few places that'll need the change. I'm going to hold onto this PR and coordinate the changes to make sure the transition is as smooth as possible.

**Comment by ralphtheninja** [comment]
Aye, I'm working on `scuttlebot` now.

**Comment by ralphtheninja** [comment]
This can still be merged though. Just don't have to publish it yet :)

**Comment by pfraze** [comment]
I'll do both at once :)

**Comment by ralphtheninja** [comment]
:+1: You're the boss :)

**Comment by pfraze** [comment]
couldnt merge so just did it in separate commits

bumped package.json to `1.0.3` but couldnt publish, @dominictarr I think that's up to you

**Comment by dominictarr** [comment]
published, and added you @pfraze

**Pull request closed without merging**
